# -*- coding: utf-8 -*-
"""F6 环境备份与迁移：core.backup_bundle 导出 / 恢复 / 回滚 / dry-run。

用假 nginx 布局与打桩的 PhpManager / hosts，不触碰真实环境与系统 hosts。
"""
import os
import tempfile
import types
import unittest
import zipfile
from unittest import mock

from core import backup_bundle
from core.vhost_manager import VhostManager
from tests.fakes import FAILED, make_layout, read

VHOST = "server { listen 80; server_name app.test; root /tmp/app; }\n"


class FakeConfig:
    def __init__(self, path: str):
        self.config_path = path


class FakePhpManager:
    def __init__(self, versions):
        self._v = versions

    def scan_versions(self):
        return self._v


class BackupBundleTest(unittest.TestCase):
    def setUp(self):
        self.dir = tempfile.TemporaryDirectory()
        self.root = self.dir.name
        self.ng = make_layout(self.root)
        os.makedirs(self.ng.vhost_dir, exist_ok=True)
        self.cfg_path = os.path.join(self.root, "config.json")
        with open(self.cfg_path, "w", encoding="utf-8") as f:
            f.write('{"ports": {}}')
        self.conf = os.path.join(self.ng.vhost_dir, "app.test.conf")
        with open(self.conf, "w", encoding="utf-8") as f:
            f.write(VHOST)
        self.ini = os.path.join(self.root, "php82", "php.ini")
        os.makedirs(os.path.dirname(self.ini), exist_ok=True)
        with open(self.ini, "w", encoding="utf-8") as f:
            f.write("memory_limit = 128M\n")
        self.cfg = FakeConfig(self.cfg_path)
        self.zip_path = os.path.join(self.root, "env.zip")
        self._patch()

    def tearDown(self):
        self.dir.cleanup()

    def _patch(self):
        def vm_factory(config=None):
            vm = VhostManager(self.cfg)
            vm.nginx = self.ng
            return vm

        p = mock.patch.object(backup_bundle, "VhostManager", vm_factory)
        p.start()
        self.addCleanup(p.stop)

        def php_factory(config=None):
            return FakePhpManager([types.SimpleNamespace(name="php82", ini=self.ini)])

        p2 = mock.patch.object(backup_bundle, "PhpManager", php_factory)
        p2.start()
        self.addCleanup(p2.stop)

        p3 = mock.patch.object(backup_bundle, "default_config_path",
                               return_value=self.cfg_path)
        p3.start()
        self.addCleanup(p3.stop)

        p4 = mock.patch.object(backup_bundle.hosts_manager, "read_text",
                               return_value="# >>> phpvm-managed (auto generated by phpvm, do not edit) >>>\n"
                                            "127.0.0.1 app.test    # phpvm-managed: auto site mapping\n"
                                            "# <<< phpvm-managed <<<\n")
        p4.start()
        self.addCleanup(p4.stop)

    def test_export_writes_expected_entries(self):
        res = backup_bundle.export_bundle(self.zip_path, self.cfg)
        self.assertTrue(res["ok"], res)
        with zipfile.ZipFile(self.zip_path) as z:
            names = set(z.namelist())
        self.assertIn("manifest.json", names)
        self.assertIn("config.json", names)
        self.assertIn("nginx/nginx.conf", names)
        self.assertIn("nginx/vhost/app.test.conf", names)
        self.assertIn("php/php82/php.ini", names)
        self.assertIn("hosts.phpvm.txt", names)
        self.assertEqual(res["counts"]["vhost"], 1)

    def test_restore_roundtrip(self):
        backup_bundle.export_bundle(self.zip_path, self.cfg)
        with open(self.conf, "w", encoding="utf-8") as f:
            f.write("BROKEN\n")
        res = backup_bundle.restore_bundle(self.zip_path, self.cfg)
        self.assertTrue(res["ok"], res)
        self.assertEqual(read(self.conf), VHOST)
        self.assertEqual(read(self.cfg_path), '{"ports": {}}')

    def test_restore_rolls_back_on_validate_failure(self):
        backup_bundle.export_bundle(self.zip_path, self.cfg)
        with open(self.conf, "w", encoding="utf-8") as f:
            f.write("BROKEN\n")
        self.ng.test_output = FAILED
        res = backup_bundle.restore_bundle(self.zip_path, self.cfg)
        self.assertFalse(res["ok"])
        self.assertTrue(res.get("rolled_back"))
        self.assertEqual(read(self.conf), "BROKEN\n", "回滚应还原恢复前的文件")

    def test_restore_dry_run_does_not_write(self):
        backup_bundle.export_bundle(self.zip_path, self.cfg)
        with open(self.conf, "w", encoding="utf-8") as f:
            f.write("BROKEN\n")
        res = backup_bundle.restore_bundle(self.zip_path, self.cfg, dry_run=True)
        self.assertTrue(res["ok"], res)
        self.assertTrue(res["dry_run"])
        self.assertGreater(res["count"], 0)
        self.assertEqual(read(self.conf), "BROKEN\n")

    def test_restore_rejects_non_phpvm_zip(self):
        bogus = os.path.join(self.root, "bogus.zip")
        with zipfile.ZipFile(bogus, "w") as z:
            z.writestr("hello.txt", "hi")
        res = backup_bundle.restore_bundle(bogus, self.cfg)
        self.assertFalse(res["ok"])
        self.assertIn("manifest", res["message"])

    def test_restore_missing_file(self):
        res = backup_bundle.restore_bundle(os.path.join(self.root, "nope.zip"), self.cfg)
        self.assertFalse(res["ok"])


if __name__ == "__main__":
    unittest.main()
