# -*- coding: utf-8 -*-
"""hosts 文件管理：把站点域名自动映射到本机（127.0.0.1）。

定位：
- Windows：%SystemRoot%\\System32\\drivers\\etc\\hosts；
- macOS / Linux：/etc/hosts。

写入策略：
- 追加带 phpvm 标记的块，便于人工识别 / 清理；
- 已指向目标 IP 的域名跳过，不产生重复条目；
- 已指向其它 IP 的域名不做覆盖（避免误改用户手写映射），只提示；
- 普通追加失败（无写权限）时按平台走提权写入：
    Windows → PowerShell Start-Process -Verb RunAs（弹 UAC）；
    macOS   → osascript `do shell script ... with administrator privileges`（弹系统授权框）；
    其它 Linux → 返回错误提示，交用户手动处理。
"""
import base64
import os
import re
import sys

from . import process_utils as pu
from .config import IS_WIN
from .i18n import t

MANAGED_TAG = "phpvm-managed"
DEFAULT_IP = "127.0.0.1"

# IPv4 / IPv6 地址（用于把每行首个 token 识别成 IP）
_RE_IP = re.compile(r"^[0-9.]+$|^[0-9a-fA-F:]+$")


def hosts_path() -> str:
    """返回当前平台 hosts 文件绝对路径。"""
    if IS_WIN:
        return os.path.join(
            os.environ.get("SystemRoot", r"C:\Windows"),
            "System32", "drivers", "etc", "hosts",
        )
    return "/etc/hosts"


def read_text() -> str:
    """读取 hosts 全文；失败抛 OSError。"""
    with open(hosts_path(), "r", encoding="utf-8", errors="replace") as f:
        return f.read()


def parse_mapping(text: str) -> dict[str, str]:
    """解析 hosts 文本 → {小写域名: ip}（跳过注释行；多个域名逐行收集）。"""
    mapping: dict[str, str] = {}
    for raw in text.splitlines():
        content = raw.split("#", 1)[0].strip()
        if not content:
            continue
        parts = content.split()
        if not parts:
            continue
        if _RE_IP.match(parts[0]):
            ip, names = parts[0], parts[1:]
        else:
            # 罕见顺序（hostname 在前）：视首个 token 为域名，不识别 IP
            ip, names = "", parts
        for name in names:
            if name:
                mapping.setdefault(name.lower(), ip)
    return mapping


def get_domain_ip(domain: str) -> str | None:
    """返回域名当前在 hosts 中映射的 IP；未配置返回 None。"""
    domain = domain.strip().lower()
    if not domain:
        return None
    try:
        text = read_text()
    except OSError:
        return None
    return parse_mapping(text).get(domain)


def mapping_for_domains(domains: list[str]) -> dict[str, str | None]:
    """批量查询多个域名的 hosts 映射（一次读取）。返回 {域名: ip | None}。"""
    out: dict[str, str | None] = {}
    keys = {d.strip().lower() for d in domains if d and d.strip()}
    if not keys:
        return out
    try:
        mapping = parse_mapping(read_text())
    except OSError:
        return {k: None for k in keys}
    for k in keys:
        out[k] = mapping.get(k)
    return out


# --------------------------------------------------------------------------- #
# 写入
# --------------------------------------------------------------------------- #
def _block_text(domains: list[str], ip: str = DEFAULT_IP) -> str:
    """把待追加域名组织成带标记的文本块（不保证结尾换行）。"""
    line = f"{ip} {' '.join(domains)}    # {MANAGED_TAG}: auto site mapping"
    return (
        f"# >>> {MANAGED_TAG} (auto generated by phpvm, do not edit) >>>\n"
        f"{line}\n"
        f"# <<< {MANAGED_TAG} <<<\n"
    )


def ensure_entries(domains: list[str], ip: str = DEFAULT_IP) -> dict:
    """确保域名已映射到本机 ip。返回结果字典：
    {ok, elevated, added[], already[], conflict[], message}
    """
    todo: list[str] = []
    already: list[str] = []
    conflict: list[str] = []
    try:
        mapping = parse_mapping(read_text())
    except OSError as e:
        return {"ok": False, "elevated": False, "added": [], "already": [],
                "conflict": [], "message": t("读取 hosts 失败：{err}", err=e)}
    for d in domains:
        d = (d or "").strip().lower()
        if not d:
            continue
        cur = mapping.get(d)
        if cur is None:
            todo.append(d)
        elif cur == ip:
            already.append(d)
        else:
            conflict.append(d)

    if not todo:
        detail = "、".join(already) or "—"
        if conflict:
            msg = t("hosts 无需修改（已指向 {ip}：{detail}）；以下域名指向其它 IP，未改动：{others}",
                    ip=ip, detail=detail, others=", ".join(conflict))
        else:
            msg = t("hosts 无需修改（已指向 {ip}：{detail}）", ip=ip, detail=detail)
        return {"ok": True, "elevated": False, "added": [], "already": already,
                "conflict": conflict, "message": msg}

    block = _block_text(todo, ip)
    path = hosts_path()
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            existed = f.read()
        if existed and not existed.endswith("\n"):
            block = "\n" + block
        with open(path, "a", encoding="ascii", errors="replace") as f:
            f.write(block)
        return {"ok": True, "elevated": False, "added": todo, "already": already,
                "conflict": conflict,
                "message": t("已写入 hosts：{ip} {doms}", ip=ip, doms=" ".join(todo))}
    except PermissionError:
        return _write_elevated(block, todo, already, conflict)
    except OSError as e:
        return {"ok": False, "elevated": False, "added": [], "already": already,
                "conflict": conflict, "message": t("写入 hosts 失败：{err}", err=e)}


def _write_elevated(block: str, todo: list[str], already: list[str],
                    conflict: list[str]) -> dict:
    """普通追加无权限时，按平台提权写入。"""
    path = hosts_path()
    b64 = base64.b64encode(block.encode("utf-8")).decode("ascii")
    if IS_WIN:
        ps = (
            "param([string]$b64)\n"
            "$h = Join-Path $env:SystemRoot 'System32\\drivers\\etc\\hosts'\n"
            "$t = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($b64))\n"
            "$t = $t -replace \"`n\",\"`r`n\"\n"
            "Add-Content -LiteralPath $h -Value $t -Encoding ASCII\n"
        )
        child = base64.b64encode(ps.encode("utf-16-le")).decode("ascii")
        cmd = [
            "powershell", "-NoProfile", "-NonInteractive", "-Command",
            "Start-Process -FilePath powershell -Verb RunAs -Wait "
            "-ArgumentList '-NoProfile','-EncodedCommand','%s'" % child,
        ]
        code, out, err = pu.run_cmd(cmd, timeout=120)
        if code == 0:
            return {"ok": True, "elevated": True, "added": todo, "already": already,
                    "conflict": conflict,
                    "message": t("已通过管理员授权写入 hosts：{doms}", doms=" ".join(todo))}
        return {"ok": False, "elevated": True, "added": [], "already": already,
                "conflict": conflict,
                "message": t("写入 hosts 需要管理员权限（授权被取消或失败）。\n"
                             "可手动打开 hosts 文件追加：127.0.0.1 {doms}", doms=" ".join(todo))}
    if sys.platform == "darwin":
        cmd = [
            "osascript", "-e",
            f'do shell script "echo {b64} | base64 -D >> {path}" '
            "with administrator privileges",
        ]
        code, out, err = pu.run_cmd(cmd, timeout=180)
        if code == 0:
            return {"ok": True, "elevated": True, "added": todo, "already": already,
                    "conflict": conflict,
                    "message": t("已通过系统授权写入 hosts：{doms}", doms=" ".join(todo))}
        return {"ok": False, "elevated": True, "added": [], "already": already,
                "conflict": conflict,
                "message": t("写入 /etc/hosts 需要管理员授权（已取消或失败：{err}）。\n"
                             "可手动编辑 /etc/hosts 追加：127.0.0.1 {doms}",
                             err=err.strip() or t("无输出"), doms=" ".join(todo))}
    # 其它 Linux：无密码弹框手段，交用户手动处理
    return {"ok": False, "elevated": False, "added": [], "already": already,
            "conflict": conflict,
            "message": t("写入 /etc/hosts 需要 root 权限。请在终端手动执行：\n"
                         "sudo sh -c 'echo \"127.0.0.1 {doms}\" >> /etc/hosts'",
                         doms=" ".join(todo))}
